[package]
name = "axios_data"
version = "0.0.10"
edition = "2024"
rust-version = "1.85.0"
description = "Core data structures and I/O methods"
documentation = "https://docs.rs/axios-rs/"
readme = "README.md"
repository = "https://github.com/IFFranciscoME/axios-rs"
license = "Apache-2.0"
keywords = ["crypto", "defi", "lending", "math", "trading"]
categories = ["data-structures", "development-tools", "finance", "simulation"]
exclude = ["*.log", ".github", "Makefile.toml", "assets/*", "tags"]
include = ["../katex-header.html", "Cargo.toml", "README.md", "src/**/*"]
publish = true

[package.metadata.docs.rs]
private-doc = true

[lib]
name = "axios_data"
path = "src/lib.rs"

[[test]]
name = "test_liquidations"
path = "test/bybit/liquidations/liquidations_test.rs"

[[test]]
name = "test_t2_market_state"
path = "test/onchain/morpho/test_t2_market_state.rs"

[[test]]
name = "test_t3_irm_state"
path = "test/onchain/morpho/test_t3_irm_state.rs"

[dependencies]
async-rate-limiter = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
config = { workspace = true }
csv = { workspace = true }
futures-util = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
toml = { workspace = true }
url = { workspace = true }
